name: flutter_cataas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  anyhow: ^1.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  glados: ^1.1.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
