name: flutter_cataas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  anyhow: ^1.2.1
  collection: ^1.18.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  intl: any
  meta: ^1.10.0
  neubrutalism_ui: ^2.0.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  talker_bloc_logger: ^4.1.5
  talker_dio_logger: ^4.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  glados: ^1.1.6
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
